-- =============================================
-- TỔNG HỢP CÁC VIEW
-- =============================================

USE S03_QLTKNH;
GO

-- =============================================
-- I. VIEW LẤY THÔNG TIN TỪ 2 BẢNG TRỞ LÊN
-- =============================================

-- 1. View thông tin khách hàng (2 bảng)
CREATE OR ALTER VIEW V_ThongTinKH AS
SELECT 
    KHACHHANG.MaKH, 
    KHACHHANG.TenKH, 
    KHACHHANG.SDT, 
    KHACHHANG.Email, 
    KHACHHANG.MaNVTiepTan, 
    NHANVIEN.TenNV
FROM KHACHHANG, NHANVIEN
WHERE KHACHHANG.MaNVTiepTan = NHANVIEN.MaNV;
GO

-- 2. View tài khoản khách hàng (2 bảng)
CREATE OR ALTER VIEW V_TaiKhoanKH AS
SELECT 
    TAIKHOAN.MaTK, 
    TAIKHOAN.SoTK, 
    KHACHHANG.TenKH, 
    TAIKHOAN.SoDu, 
    TAIKHOAN.TrangThai
FROM TAIKHOAN, KHACHHANG
WHERE TAIKHOAN.MaKH = KHACHHANG.MaKH;
GO

-- 3. View sổ tiết kiệm chi tiết (6 bảng)
CREATE OR ALTER VIEW V_STKChiTiet AS
SELECT
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    LOAIHINHTK.TenLoaiHinh,
    HINHTHUCGUI.TenHTGui,
    HINHTHUCTRALAI.TenHTTraLai,
    SOTIETKIEM.TienGoc,
    SOTIETKIEM.TrangThai
FROM SOTIETKIEM, TAIKHOAN, KHACHHANG, LOAIHINHTK, HINHTHUCGUI, HINHTHUCTRALAI
WHERE SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
  AND SOTIETKIEM.MaLoaiHinh = LOAIHINHTK.MaLoaiHinh
  AND SOTIETKIEM.MaHTGui = HINHTHUCGUI.MaHTGui
  AND SOTIETKIEM.MaHTTraLai = HINHTHUCTRALAI.MaHTTraLai;
GO

-- 4. View sổ tiết kiệm đang hoạt động (3 bảng)
CREATE OR ALTER VIEW V_STK_DANGHOATDONG AS
SELECT 
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    SOTIETKIEM.NgayMoSo,
    SOTIETKIEM.NgayDaoHan,
    SOTIETKIEM.TrangThai
FROM SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
  AND SOTIETKIEM.TrangThai = N'Đang hoạt động';
GO

-- 5. View sổ tiết kiệm sắp đáo hạn (3 bảng)
CREATE OR ALTER VIEW V_STK_SAPDAOHAN AS
SELECT 
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    SOTIETKIEM.NgayMoSo,
    SOTIETKIEM.NgayDaoHan,
    SOTIETKIEM.TrangThai
FROM SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
  AND SOTIETKIEM.NgayDaoHan BETWEEN GETDATE() AND DATEADD(DAY,7,GETDATE());
GO

-- 6. View giao dịch nộp tiền (5 bảng)
CREATE OR ALTER VIEW V_GDNOPTIEN AS
SELECT 
    GIAODICHNOP.MaGDnop,
    KHACHHANG.TenKH,
    NHANVIEN.TenNV,
    GIAODICHNOP.SoTienNop,
    GIAODICHNOP.NgayGD,
    GIAODICHNOP.HTThanhToan
FROM GIAODICHNOP, SOTIETKIEM, TAIKHOAN, KHACHHANG, NHANVIEN
WHERE GIAODICHNOP.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
  AND GIAODICHNOP.MaNVThucHien = NHANVIEN.MaNV;
GO

-- 7. View giao dịch rút tiền (5 bảng)
CREATE OR ALTER VIEW V_GDRUTTIEN AS
SELECT 
    GIAODICHRUT.MaGDrut,
    KHACHHANG.TenKH,
    NHANVIEN.TenNV,
    GIAODICHRUT.SoTienRut,
    GIAODICHRUT.NgayGD,
    GIAODICHRUT.LaiNhanDuoc
FROM GIAODICHRUT, SOTIETKIEM, TAIKHOAN, KHACHHANG, NHANVIEN
WHERE GIAODICHRUT.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
  AND GIAODICHRUT.MaNVThucHien = NHANVIEN.MaNV;
GO

-- 8. View lịch sử giao dịch theo sổ (4 bảng)
CREATE OR ALTER VIEW V_LichSuGD_STK AS
SELECT 
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    GIAODICHNOP.NgayGD,
    N'Gửi tiền' AS LoaiGD,
    GIAODICHNOP.SoTienNop AS SoTien
FROM GIAODICHNOP, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE GIAODICHNOP.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH

UNION ALL

SELECT 
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    GIAODICHRUT.NgayGD,
    N'Rút tiền' AS LoaiGD,
    GIAODICHRUT.SoTienRut AS SoTien
FROM GIAODICHRUT, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE GIAODICHRUT.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH;
GO

-- 9. View bảng tính lãi chi tiết (4 bảng)
CREATE OR ALTER VIEW V_BANGTINHLAICHITIET AS
SELECT 
    BANGTINHLAI.MaTinhLai,
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    BANGTINHLAI.LaiSuatApDung,
    BANGTINHLAI.LaiThangNay,
    BANGTINHLAI.LaiTichLuy
FROM BANGTINHLAI, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE BANGTINHLAI.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH;
GO

-- 10. View số dư sổ tiết kiệm (4 bảng)
CREATE OR ALTER VIEW V_SODUSTK AS
SELECT 
    SOTIETKIEM.MaSTK,
    KHACHHANG.TenKH,
    BANGSODU.SoDuGoc,
    BANGSODU.LaiTichLuy,
    BANGSODU.SoDuThucTe
FROM BANGSODU, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE BANGSODU.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH;
GO

-- 11. View tổng hợp số dư (4 bảng)
CREATE OR ALTER VIEW V_TONGHOPSODU AS
SELECT 
    KHACHHANG.MaKH,
    KHACHHANG.TenKH,
    SUM(BANGSODU.SoDuThucTe) AS TongSoDu
FROM BANGSODU, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE BANGSODU.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
GROUP BY KHACHHANG.MaKH, KHACHHANG.TenKH;
GO

-- 12. View chi tiết báo cáo (4 bảng)
CREATE OR ALTER VIEW V_BaoCaoChiTiet AS
SELECT 
    BAOCAO.MaBaoCao,
    KHACHHANG.TenKH,
    BAOCAO.NgayBaoCao,
    BAOCAO.LoaiBaoCao,
    BAOCAO.SoDuHienTai
FROM BAOCAO, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE BAOCAO.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH;
GO

-- 13. View báo cáo theo khách hàng (4 bảng)
CREATE OR ALTER VIEW V_BaoCaoTheoKH AS
SELECT 
    KHACHHANG.MaKH,
    KHACHHANG.TenKH,
    SUM(BAOCAO.TongTienGui) AS TongTienGui,
    SUM(BAOCAO.TongLaiNhan) AS TongLaiNhan,
    SUM(BAOCAO.SoDuHienTai) AS TongSoDu
FROM BAOCAO, SOTIETKIEM, TAIKHOAN, KHACHHANG
WHERE BAOCAO.MaSTK = SOTIETKIEM.MaSTK
  AND SOTIETKIEM.MaTK = TAIKHOAN.MaTK
  AND TAIKHOAN.MaKH = KHACHHANG.MaKH
GROUP BY KHACHHANG.MaKH, KHACHHANG.TenKH;
GO

-- 14. View báo cáo theo nhân viên (2 bảng)
CREATE OR ALTER VIEW V_BaoCaoTheoNV AS
SELECT 
    NHANVIEN.MaNV,
    NHANVIEN.TenNV,
    COUNT(BAOCAO.MaSTK) AS SoLuongBaoCao,
    SUM(BAOCAO.TongTienGui) AS TongTienGui
FROM BAOCAO, NHANVIEN
WHERE BAOCAO.MaNVTao = NHANVIEN.MaNV
GROUP BY NHANVIEN.MaNV, NHANVIEN.TenNV;
GO

-- 15. View khách hàng không hoạt động (4 bảng)
CREATE OR ALTER VIEW V_KhachHangKhongHoatDong_ChiTiet AS
SELECT 
    KHACHHANG.MaKH,
    KHACHHANG.TenKH,
    KHACHHANG.SDT,
    KHACHHANG.Email,
    TAIKHOAN.MaTK,
    TAIKHOAN.SoTK,
    TAIKHOAN.SoDu,
    TAIKHOAN.TrangThai AS TrangThaiTaiKhoan,
    COUNT(SOTIETKIEM.MaSTK) AS SoLuongSTK,
    GiaoDichCuoi.NgayGDCuoi,
    DATEDIFF(DAY, GiaoDichCuoi.NgayGDCuoi, GETDATE()) AS SoNgayKhongGiaoDich
FROM KHACHHANG, TAIKHOAN, SOTIETKIEM,
    (SELECT GiaoDichTongHop.MaSTK, MAX(GiaoDichTongHop.NgayGD) AS NgayGDCuoi
     FROM (SELECT GIAODICHNOP.MaSTK, GIAODICHNOP.NgayGD FROM GIAODICHNOP
           UNION ALL
           SELECT GIAODICHRUT.MaSTK, GIAODICHRUT.NgayGD FROM GIAODICHRUT) AS GiaoDichTongHop
     GROUP BY GiaoDichTongHop.MaSTK) AS GiaoDichCuoi
WHERE KHACHHANG.MaKH = TAIKHOAN.MaKH
  AND TAIKHOAN.MaTK = SOTIETKIEM.MaTK
  AND SOTIETKIEM.MaSTK = GiaoDichCuoi.MaSTK
  AND (TAIKHOAN.TrangThai IN (N'Không hoạt động', N'Tạm khóa', N'Đóng băng')
       OR DATEDIFF(DAY, GiaoDichCuoi.NgayGDCuoi, GETDATE()) > 180)
GROUP BY KHACHHANG.MaKH, KHACHHANG.TenKH, KHACHHANG.SDT, KHACHHANG.Email,
         TAIKHOAN.MaTK, TAIKHOAN.SoTK, TAIKHOAN.SoDu, TAIKHOAN.TrangThai,
         GiaoDichCuoi.NgayGDCuoi;
GO

-- 16. View khách hàng tiềm năng (4 bảng)
CREATE OR ALTER VIEW V_KhachHangTiemNang AS
SELECT 
    KHACHHANG.MaKH,
    KHACHHANG.TenKH,
    COUNT(SOTIETKIEM.MaSTK) AS SoLuongSTK,
    SUM(BANGSODU.SoDuThucTe) AS TongSoDu
FROM KHACHHANG, TAIKHOAN, SOTIETKIEM, BANGSODU
WHERE KHACHHANG.MaKH = TAIKHOAN.MaKH
  AND TAIKHOAN.MaTK = SOTIETKIEM.MaTK
  AND SOTIETKIEM.MaSTK = BANGSODU.MaSTK
GROUP BY KHACHHANG.MaKH, KHACHHANG.TenKH
HAVING COUNT(SOTIETKIEM.MaSTK) >= 2 OR SUM(BANGSODU.SoDuThucTe) >= 50000000;
GO

-- =============================================
-- II. VIEW MỚI: TỔNG HỢP SỔ TIẾT KIỆM THEO KHÁCH HÀNG
-- =============================================

-- 17. View tổng hợp sổ tiết kiệm theo khách hàng (4 bảng)
CREATE OR ALTER VIEW V_TongHopSTK_KH AS
SELECT 
    KHACHHANG.MaKH,
    KHACHHANG.TenKH,
    KHACHHANG.SDT,
    KHACHHANG.Email,
    COUNT(SOTIETKIEM.MaSTK) AS TongSoSTK,
    SUM(SOTIETKIEM.TienGoc) AS TongTienGoc,
    SUM(BANGSODU.SoDuThucTe) AS TongSoDuHienTai,
    MAX(SOTIETKIEM.NgayMoSo) AS NgayMoSoGanNhat
FROM KHACHHANG, TAIKHOAN, SOTIETKIEM, BANGSODU
WHERE KHACHHANG.MaKH = TAIKHOAN.MaKH
  AND TAIKHOAN.MaTK = SOTIETKIEM.MaTK
  AND SOTIETKIEM.MaSTK = BANGSODU.MaSTK
  AND SOTIETKIEM.TrangThai = N'Đang hoạt động'
GROUP BY KHACHHANG.MaKH, KHACHHANG.TenKH, KHACHHANG.SDT, KHACHHANG.Email;
GO

-- =============================================
-- III. VIEW TỔNG HỢP GIAO DỊCH (2 bảng)
-- =============================================

-- 18. View tổng hợp giao dịch (2 bảng)
CREATE OR ALTER VIEW V_TONGHOPGD AS
SELECT 
    GIAODICHNOP.MaGDnop AS MaGD,
    GIAODICHNOP.MaSTK,
    GIAODICHNOP.SoTienNop AS SoTien,
    N'Nộp tiền' AS LoaiGD,
    GIAODICHNOP.NgayGD
FROM GIAODICHNOP
UNION ALL
SELECT 
    GIAODICHRUT.MaGDrut AS MaGD,
    GIAODICHRUT.MaSTK,
    GIAODICHRUT.SoTienRut AS SoTien,
    N'Rút tiền' AS LoaiGD,
    GIAODICHRUT.NgayGD
FROM GIAODICHRUT;
GO

-- 19. View giao dịch theo ngày (2 bảng)
CREATE OR ALTER VIEW V_GD_THEONGAY AS
SELECT 
    GIAODICHNOP.MaGDnop AS MaGD,
    GIAODICHNOP.MaSTK,
    GIAODICHNOP.NgayGD,
    GIAODICHNOP.SoTienNop AS SoTien,
    N'Nộp tiền' AS LoaiGD
FROM GIAODICHNOP
WHERE CONVERT(DATE, GIAODICHNOP.NgayGD) = CONVERT(DATE, GETDATE())

UNION ALL

SELECT 
    GIAODICHRUT.MaGDrut AS MaGD,
    GIAODICHRUT.MaSTK,
    GIAODICHRUT.NgayGD,
    GIAODICHRUT.SoTienRut AS SoTien,
    N'Rút tiền' AS LoaiGD
FROM GIAODICHRUT
WHERE CONVERT(DATE, GIAODICHRUT.NgayGD) = CONVERT(DATE, GETDATE());
GO